import { describe, it, expect } from "vitest";
import { parseListQuery } from "@/platform/list-query.js";
import { INVOICE_LIST_WHITELIST } from "@/modules/invoices/schema.js";
import { PROFORMA_LIST_WHITELIST } from "@/modules/proforma/schema.js";
import { EXPENSE_LIST_WHITELIST } from "@/modules/expenses/schema.js";

/**
 * The recurring-profile detail page lists the documents a profile generated by
 * filtering each doc collection on `sourceRecurringProfileId` (the back-ref the
 * worker stamps on every occurrence). That field must stay filterable on all
 * three generated doc types, or the "generated documents" table silently empties.
 */
describe("generated-docs filter (sourceRecurringProfileId)", () => {
  const cases = [
    ["invoices", INVOICE_LIST_WHITELIST],
    ["proformas", PROFORMA_LIST_WHITELIST],
    ["expenses", EXPENSE_LIST_WHITELIST],
  ] as const;

  for (const [name, whitelist] of cases) {
    it(`${name}: accepts the filter and maps it to an exact match`, () => {
      const { filter } = parseListQuery({ sourceRecurringProfileId: "p1" }, whitelist);
      expect(filter.sourceRecurringProfileId).toBe("p1");
    });
  }

  it("still rejects a non-whitelisted field", () => {
    expect(() => parseListQuery({ nope: "x" }, INVOICE_LIST_WHITELIST)).toThrowError();
  });
});
